version: "3.8"

services:
  api:
    image: nayeembd/simple-node-app:${COMMIT_HASH}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
    restart: on-failure:10
    healthcheck:
      test: curl --fail http://localhost:4000/health
      start_period: 2s
    networks:
      - mynodeapp

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    networks:
      - mynodeapp
    volumes:
      - ./nginx.conf:/ect/nginx/nginx.conf
    depends_on:
      - api


networks:
  mynodeapp:
